---
galaxy_info:
  author: Johan Odell
  description: Ansible role for provisioning NetworkAttachmentDefinitions in OpenShift clusters
  company: Red Hat

  license: Apache-2.0

  min_ansible_version: "2.15"

  platforms:
    - name: EL
      versions:
        - "8"
        - "9"

  galaxy_tags:
    - openshift
    - kubernetes
    - networking
    - multus
    - cni
    - virtualization
    - kubevirt

dependencies: []

collections:
  - kubernetes.core
  - ansible.builtin
